import Navbar from "./components/Nav";
import "./globals.css";

import Providers from '../Providers'

export const metadata = {
  title: "QuizoPedia",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // console.log(children);

  return (

    <html lang="en">
      <body className=" bg-(--bg)">
        <Providers >
        <Navbar />
          {<main className=" pt-16 px-2 h-full w-full text-(--text-primary) ">
            {children}
          </main>}
        </Providers>
      </body>
    </html>
  );
}
