import Navbar from "./components/Nav";
import "./globals.css";

// import Provider from '../providers'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (

    <html lang="en">
      <body className=" bg-(--bg)">
        {/* <Provider> */}
        <Navbar />
        <main className=" pt-16 px-2 h-full w-full text-(--text-primary) ">
          {children}
        </main>
        {/* </Provider> */}
      </body>
    </html>
  );
}
