import Navbar from "../components/Nav.jsx";
import "./globals.css";

import Providers from '@/Providers.jsx'
import { ToastContainer } from "react-toastify";
import Footer from "@/components/Footer.jsx";

export const metadata = {
  title: "QuizoPedia",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // console.log(children);

  return (

    <html lang="en">
      <body className=" bg-[var(--bg)] overflow-x-hidden relative">
        <Providers >
          <Navbar />
          {<main className=" pt-16 px-2 h-full w-full text-(--text-primary)  ">
            {children}
            <Footer />
          </main>}
        </Providers>
        <ToastContainer
          position="top-center"
          autoClose={3000}
          hideProgressBar={false}
          newestOnTop
          closeOnClick
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="colored" // or "dark", "light"
        />
      </body>
    </html>
  );
}
